# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a38b3d5fc375f13fff1fd18c537d476d6cbf59226ec9e1b98ed093c0a4bf656d21bc9f9a7393a1d977828a04edfa1c3f658418afd6455d86fef052092bbd7e79

test:
  secret_key_base: fbe4cd36b9a53bf97855a75873a15d228f54322caad28689d42e91d6317ffff69d90c9b9e8ba0644843ec47daf669fc02a1f0e53606e59f5a4a20aabc4364483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
